/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import dao.DonDatBan_DAO;
import dao.NhanVien_DAO;
import model.DonDatBan;
import model.NhanVien;
import gui.component.ItemDonDatBan;
import gui.main.Admin_DashBoard;
import gui.main.LeTan_DashBoard;
import gui.swing.WrapLayout;
import gui.swing.table.ScrollBarCustomUI;
import java.awt.FlowLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanh Tuan
 */
public class CapNhatDonDatBan_PN extends javax.swing.JPanel {

    /**
     * Creates new form pn_timKiemCapNhatDatBan
     */
    private NhanVien nv;
    private NhanVien_DAO nv_dao = new NhanVien_DAO();
    /**
     * Creates new form pn_timKiemCapNhatDatBan
     */
    private DonDatBan_DAO donDatBan_DAO;

    public CapNhatDonDatBan_PN(Admin_DashBoard dashboard) {
        initComponents();
        this.nv = nv_dao.getNV(dashboard.getHeader().getTextMaNV());
        customItemPane();
        setWrapLayout();
        setDefaultDate();
        init();
        loadDDB();
        
    }
    
    public CapNhatDonDatBan_PN(LeTan_DashBoard dashboard) {
        initComponents();
        this.nv = nv_dao.getNV(dashboard.getHeader().getTextMaNV());
        customItemPane();
        setWrapLayout();
        setDefaultDate();
        init();
        loadDDB();
        
    }

    private void init() {
        txtDate.setDate(new Date());
        txtSDT.setText("");
        donDatBan_DAO = new DonDatBan_DAO();
        txtSDT.requestFocus();
    }

    private void customItemPane() {
        jScrollPane1.getVerticalScrollBar().setUI(new ScrollBarCustomUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new ScrollBarCustomUI());
    }

    private void setWrapLayout() {
        listDDBPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 10, 10));
    }

    private void setDefaultDate() {
        txtDate.setDate(new Date());
    }

    private void loadDDB() {
        listDDBPanel.removeAll(); // Xóa tất cả các thành phần
        listDDBPanel.revalidate(); // Cập nhật lại bố cục
        listDDBPanel.repaint(); // Vẽ lại giao diện
        ArrayList<DonDatBan> list = donDatBan_DAO.timKiemCapNhat(new SimpleDateFormat("dd/MM/yyyy").format(txtDate.getDate()), txtSDT.getText().equals("") ? null : txtSDT.getText());
        if (list != null) {
            for (DonDatBan x : list) {
                listDDBPanel.add(new ItemDonDatBan(x, nv));
            }
        }
    }

    private void refresh() {
        txtDate.setDate(new Date());
        txtSDT.setText("");
        loadDDB();
    }

    public void reload() {
        ArrayList<DonDatBan> list = donDatBan_DAO.timKiemCapNhat(new SimpleDateFormat("dd/MM/yyyy").format(txtDate.getDate()), txtSDT.getText().equals("") ? null : txtSDT.getText());
        listDDBPanel.removeAll(); // Xóa tất cả các thành phần
        listDDBPanel.revalidate(); // Cập nhật lại bố cục
        listDDBPanel.repaint(); // Vẽ lại giao diện
        if (list != null) {
            for (DonDatBan x : list) {
                listDDBPanel.add(new ItemDonDatBan(x, nv));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listDDBPanel = new javax.swing.JPanel();
        tabbedPaneCustom1 = new gui.component.TabbedPaneCustom();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollBarCustom1 = new gui.swing.menu.ScrollBarCustom();
        jLabel3 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnReset = new gui.component.Button();
        txtTimKiem = new gui.component.Button();
        txtDate = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 204, 204));

        listDDBPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout listDDBPanelLayout = new javax.swing.GroupLayout(listDDBPanel);
        listDDBPanel.setLayout(listDDBPanelLayout);
        listDDBPanelLayout.setHorizontalGroup(
            listDDBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        listDDBPanelLayout.setVerticalGroup(
            listDDBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listDDBPanel);

        tabbedPaneCustom1.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setText("Ngày đặt bàn:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("Số điện thoại:");

        txtSDT.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btnReset.setBackground(new java.awt.Color(50, 50, 50));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8-refresh-32.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtTimKiem.setBackground(new java.awt.Color(50, 50, 50));
        txtTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        txtTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8-search-32.png"))); // NOI18N
        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        txtDate.setDateFormatString("dd/MM/yyyy");
        txtDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollBarCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(scrollBarCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Lọc", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        if (txtDate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn ngày đặt bàn trước khi tìm kiếm", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            reload();
        }
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        refresh();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.component.Button btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listDDBPanel;
    private gui.swing.menu.ScrollBarCustom scrollBarCustom1;
    private gui.component.TabbedPaneCustom tabbedPaneCustom1;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtSDT;
    private gui.component.Button txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
