/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import dao.MonAn_DAO;
import gui.swing.table.TableCustom;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author THANHTRI
 */
public class TimMonAn_PN extends javax.swing.JPanel {

    /**
     * Creates new form pn_ThemNhanVien
     */
    public TimMonAn_PN() {
        initComponents();
        customTable();
        loadLoaiMon();
    }
    
    private void customTable() {
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        tabThongTinMonAn.getTableHeader().setFont(new Font("Sanserif", Font.BOLD, 12));
        tabThongTinMonAn.getTableHeader().setBackground(new Color(50, 50, 50));
        tabThongTinMonAn.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()  {

        lblTieuChiTimKiem = new javax.swing.JLabel();
        cmbTieuChiTimKiem = new javax.swing.JComboBox<>();
        cmbTieuChiSapXep = new javax.swing.JComboBox<>();
        cmbLoaiMonAn = new javax.swing.JComboBox<>();
        radTang = new javax.swing.JRadioButton();
        radGiam = new javax.swing.JRadioButton();
        txtNhapThongTin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabThongTinMonAn = new javax.swing.JTable();
        lblSapXep = new javax.swing.JLabel();
        lblLoaiMonAn = new javax.swing.JLabel();
        lblNhapThongTin = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        cmbTrangThai = new javax.swing.JComboBox<>();
        btnTimKiem = new gui.component.Button();
        btnReset = new gui.component.Button();
        group = new javax.swing.ButtonGroup();

        group.add(radTang);
        group.add(radGiam);

        setBackground(java.awt.Color.white);
        setForeground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(980, 768));
        setVerifyInputWhenFocusTarget(false);

        lblTieuChiTimKiem.setBackground(java.awt.Color.black);
        lblTieuChiTimKiem.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTieuChiTimKiem.setText("Chọn tiêu chí tìm kiếm : ");

        cmbTieuChiTimKiem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbTieuChiTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn tiêu chí tìm kiếm --", "Mã món", "Tên món" }));
        cmbTieuChiTimKiem.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbTieuChiTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTieuChiTimKiemActionPerformed(evt);
            }
        });

        cmbTieuChiSapXep.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbTieuChiSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn tiêu chí sắp xếp --", "Giá", "Phần trăm giảm", "Tên món" }));
        cmbTieuChiSapXep.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbTieuChiSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTieuChiSapXepActionPerformed(evt);
            }
        });

        cmbLoaiMonAn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbLoaiMonAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả"}));
        cmbLoaiMonAn.setName(""); // NOI18N
        cmbLoaiMonAn.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbLoaiMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoaiNhanVienActionPerformed(evt);
            }
        });

        radTang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        radTang.setText("Tăng dần");
        radTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTangActionPerformed(evt);
            }
        });

        radGiam.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        radGiam.setText("Giảm dần");
        radGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radGiamActionPerformed(evt);
            }
        });

        txtNhapThongTin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNhapThongTin.setActionCommand("<Not Set>");
        txtNhapThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNhapThongTin.setPreferredSize(new java.awt.Dimension(50, 27));
        txtNhapThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapThongTinActionPerformed(evt);
            }
        });

        tabThongTinMonAn.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tabThongTinMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã món", "Tên món", "Giá", "Giảm giá","Loại món", "Trạng thái"
            }
        ));

        // Load data loại món



        tabThongTinMonAn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabThongTinMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabThongTinNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabThongTinMonAn);

        lblSapXep.setBackground(java.awt.Color.black);
        lblSapXep.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblSapXep.setText("Sắp xếp :");

        lblLoaiMonAn.setBackground(java.awt.Color.black);
        lblLoaiMonAn.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblLoaiMonAn.setText("Loại món ăn :");

        lblNhapThongTin.setBackground(java.awt.Color.black);
        lblNhapThongTin.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblNhapThongTin.setText("Nhập thông tin :");

        lblTrangThai.setBackground(java.awt.Color.black);
        lblTrangThai.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTrangThai.setText("Trạng thái:");

        cmbTrangThai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang hoạt động", "Dừng hoạt động" }));
        cmbTrangThai.setName(""); // NOI18N
        cmbTrangThai.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoaiNhanVien1ActionPerformed(evt);
            }
        });
        btnTimKiem.setBackground(new java.awt.Color(50, 50, 50));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8-search-32.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnReset.setBackground(new java.awt.Color(50, 50, 50));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8-refresh-32.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTieuChiTimKiem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTieuChiSapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNhapThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbTieuChiTimKiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTrangThai))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbLoaiMonAn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radTang)
                                .addGap(18, 18, 18)
                                .addComponent(radGiam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cmbTieuChiSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLoaiMonAn)
                                    .addComponent(cmbLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTrangThai)
                                    .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTieuChiTimKiem)
                                    .addComponent(cmbTieuChiTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNhapThongTin)
                                    .addComponent(txtNhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(lblSapXep)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radTang)
                        .addComponent(radGiam)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnTimKiemActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnResetActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTieuChiTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTieuChiTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTieuChiTimKiemActionPerformed

    private void txtNhapThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapThongTinActionPerformed

    private void radTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radTangActionPerformed

    private void radGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radGiamActionPerformed

    private void cmbLoaiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoaiNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLoaiNhanVienActionPerformed

    private void cmbTieuChiSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTieuChiSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTieuChiSapXepActionPerformed

    private void cmbLoaiNhanVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoaiNhanVien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLoaiNhanVien1ActionPerformed

    private void tabThongTinNhanVienMouseClicked(java.awt.event.MouseEvent evt) {                                                 

     
    }


    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        System.out.println("btnTimKiemActionPerformed");
        deleteTableRow();
        if(checkValue() == false){
            System.out.println("OK");
            return;
        }
        thucThi();
    }

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        deleteTableRow();
        cmbTieuChiTimKiem.setSelectedIndex(0);
        txtNhapThongTin.setText("");
        cmbLoaiMonAn.setSelectedIndex(0);
        cmbTieuChiSapXep.setSelectedIndex(0);
        cmbTrangThai.setSelectedIndex(0);
        radTang.setSelected(false);
        radGiam.setSelected(false);
    }

    public void loadLoaiMon(){
        try{
            MonAn_DAO dao_timKiemMon = new MonAn_DAO();

            ArrayList<String> listLoaiMon = dao_timKiemMon.getLoaiMon();
            for(String loaiMon : listLoaiMon){
                cmbLoaiMonAn.addItem(loaiMon);
            }
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }



    public void thucThi() throws SQLException {
        MonAn_DAO dao_timKiemMon = new MonAn_DAO();

        ArrayList<String> listLoaiMon = dao_timKiemMon.getLoaiMon();
        for(String loaiMon : listLoaiMon){
            cmbLoaiMonAn.addItem(loaiMon);
        }


        String tieuChiTimKiem = cmbTieuChiTimKiem.getSelectedItem().toString();
        String sapXep = cmbTieuChiSapXep.getSelectedItem().toString();
        String loaiMon = cmbLoaiMonAn.getSelectedItem().toString();
        String trangThai = cmbTrangThai.getSelectedItem().toString();
        String thongTin = txtNhapThongTin.getText();
        String tieuChiSapXep = radTang.isSelected() == true ? "ASC" : "DESC";

        if(loaiMon.equals("Tất cả") == true){
            loaiMon = "";
        }

        if(trangThai.equals("Tất cả") == true){
            trangThai = "";
        }
        else if(trangThai.equals("Đang hoạt động") == true){
            trangThai = "1";
        }
        else if(trangThai.equals("Dừng hoạt động") == true){
            trangThai = "0";
        }



        if(sapXep.equals("-- Chọn tiêu chí sắp xếp --") == true){
            sapXep = "";
        }
        else if(sapXep.equals("Giá") == true){
            sapXep = "gia";
        }
        else if(sapXep.equals("Phần trăm giảm") == true){
            sapXep = "giaGia";
        }
        else if(sapXep.equals("Tên món") == true){
            sapXep = "tenMA";
        }





        if(tieuChiTimKiem.equals("Mã món") == true){
            System.out.println("Mã khuyen mai");
            Object ob[] =  (Object[]) dao_timKiemMon.timMonAnTheoMa(thongTin,loaiMon,trangThai);
            if(ob == null || ob.length == 0){
                JOptionPane.showMessageDialog(null, "Không tìm thấy món ăn");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tabThongTinMonAn.getModel();
            ob[2] = dinhDangVND(Double.parseDouble(ob[2].toString()));
            model.addRow(ob);
        }
        else if(tieuChiTimKiem.equals("Tên món") == true){
            System.out.println("Tên khuyến mãi");
            ArrayList<Object[]> list = dao_timKiemMon.timKiemMonTheoTen(thongTin,loaiMon,trangThai,sapXep,tieuChiSapXep);
            if(list.size() == 0){
                JOptionPane.showMessageDialog(null, "Không tìm thấy món ăn");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tabThongTinMonAn.getModel();
            for(Object[] ob : list){
                ob[2] = dinhDangVND(Double.parseDouble(ob[2].toString()));
                model.addRow(ob);
            }
        }


    }

    public void deleteTableRow(){
        DefaultTableModel model = (DefaultTableModel) tabThongTinMonAn.getModel();
        model.getDataVector().removeAllElements();
    }

    public boolean checkValue(){
        String txtTieuChiTimKiem = cmbTieuChiTimKiem.getSelectedItem().toString();
        String txtSapXep = cmbTieuChiSapXep.getSelectedItem().toString();
        if(txtTieuChiTimKiem.equals("-- Chọn tiêu chí tìm kiếm --") == true){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tiêu chí tìm kiếm");
            return false;
        }
        else if(txtSapXep.equals("-- Chọn tiêu chí sắp xếp --") == false && (radGiam.isSelected() == false && radTang.isSelected() == false)){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tiêu chí sắp xếp");
            return false;
        }
        return true;

    }
    
    public String dinhDangVND(double x){
        DecimalFormat decimalFormat = new DecimalFormat("#,###");
        String formatted = decimalFormat.format(x).replace(",", " ");

        return formatted + " VNĐ";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.component.Button btnReset;
    private gui.component.Button btnTimKiem;
    private javax.swing.JComboBox<String> cmbLoaiMonAn;
    private javax.swing.JComboBox<String> cmbTrangThai;
    private javax.swing.JComboBox<String> cmbTieuChiSapXep;
    private javax.swing.JComboBox<String> cmbTieuChiTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoaiMonAn;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblNhapThongTin;
    private javax.swing.JLabel lblSapXep;
    private javax.swing.JLabel lblTieuChiTimKiem;
    private javax.swing.JRadioButton radGiam;
    private javax.swing.JRadioButton radTang;
    private javax.swing.JTable tabThongTinMonAn;
    private javax.swing.JTextField txtNhapThongTin;
    private javax.swing.ButtonGroup group;
    // End of variables declaration//GEN-END:variables


}
