package gui.component;

import java.awt.*;

public class RowTable extends javax.swing.JPanel{
    public RowTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0};
        layout.columnWeights = new double[] {1.0, 1.0, 1.0, 1.0};
        // Set màu nền trắng
        this.setBackground(Color.WHITE);
        setLayout(layout);

    }// </editor-fold>//GEN-END:initComponents
}
