/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.component;

import model.Ban;
import model.LoaiBan;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import service.LoaiBanService;
import rmi.RMIClientManager;

/**
 *
 * @author Thanh Tuan
 */
public class ItemTable extends javax.swing.JPanel {
    private JLabel tableLable = null;
    private Ban ban = null;
    private static Map<String, ImageIcon> imageCache = new HashMap<>();
    private LoaiBanService lb_dao ;

    /**
     * Creates new form ItemTable
     */
    public ItemTable(JLabel tableLabel, Ban ban) throws Exception {
        this.lb_dao=RMIClientManager.getInstance().getLoaiBanService();
        initComponents();
        this.tableLable = tableLabel;
        this.ban = ban;
        loadBan();
    }

    public void loadBan() throws RemoteException{
        SwingUtilities.invokeLater(() -> {imgLoad("/hinhAnh/table.png");});
        LoaiBan lb = lb_dao.findById(ban.getLoaiBan().getMaLoaiBan());
        imgTable.setToolTipText(ban.getMaBan());
        tableName.setToolTipText(ban.getMaBan());
        tableName.setText("Bàn " + ban.getMaBan() +  " / " + lb.getTenLoaiBan() );
    }
    
    public void imgLoad(String path){
        // nếu bộ đệm đã có hình rồi thì load luôn
        if(imageCache.containsKey(path)){
            imgTable.setIcon(imageCache.get(path));
        }
        // còn nếu chưa có thì dùng SwingWorker để load ảnh đồng thời lưu luôn ảnh đó vào cache :33
        else{
            new SwingWorker<ImageIcon, Void>() {
                @Override
                protected ImageIcon doInBackground() throws Exception {
                    InputStream input = getClass().getResourceAsStream(path);
                    BufferedImage bufImg = ImageIO.read(input);
                    Image scaledImg = bufImg.getScaledInstance(imgTable.getWidth(), imgTable.getHeight(), Image.SCALE_SMOOTH);
                    return new ImageIcon(scaledImg);
                }

                @Override
                protected void done() {
                    try {
                        ImageIcon icon = get();
                        imageCache.put(path, icon);
                        imgTable.setIcon(icon);
                        imgTable.revalidate();
                        imgTable.repaint();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }.execute();
        }
    }
    
//    public void tableLoad(Ban ban){
//        
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        imgTable = new javax.swing.JLabel();
        tableName = new javax.swing.JLabel();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgTable.setToolTipText("img");
        imgTable.setPreferredSize(new java.awt.Dimension(165, 140));
        imgTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTableMouseClicked(evt);
            }
        });

        tableName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tableName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableName.setText("jLabel6");
        tableName.setToolTipText("name");
        tableName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(imgTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTableMouseClicked
        // TODO add your handling code here:
        LoaiBan lb = null;
        try {
            lb = lb_dao.findById(ban.getLoaiBan().getMaLoaiBan());
        } catch (RemoteException ex) {
            Logger.getLogger(ItemTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableLable.setText("Bàn " + ban.getMaBan() +  " / " + lb.getTenLoaiBan());
        tableLable.setToolTipText(ban.getMaBan());
    }//GEN-LAST:event_imgTableMouseClicked

    private void tableNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNameMouseClicked
        // TODO add your handling code here:
        LoaiBan lb = null;
        try {
            lb = lb_dao.findById(ban.getLoaiBan().getMaLoaiBan());
        } catch (RemoteException ex) {
            Logger.getLogger(ItemTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableLable.setText("Bàn " + ban.getMaBan() +  " / " + lb.getTenLoaiBan());
        tableLable.setToolTipText(ban.getMaBan());

    }//GEN-LAST:event_tableNameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgTable;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel tableName;
    // End of variables declaration//GEN-END:variables
}
