package gui.form;

import dao.DonDatBan_DAO;
import entity.NhanVien;
import gui.swing.table.TableCustom;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.SQLException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

public class HuyDonDatBan_Form extends javax.swing.JFrame {

    private String ma;
    private NhanVien nv;
    private JFrame CapNhatDonDatBan_Form;

    /**
     * Creates new form HuyDonDatBan_Form
     * @param maDDB
     * @param nv
     */
    public HuyDonDatBan_Form(String maDDB, NhanVien nv, JFrame CapNhatDonDatBan_Form) {
        this.ma = maDDB;
        this.nv = nv;
        this.CapNhatDonDatBan_Form = CapNhatDonDatBan_Form;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        load(maDDB);
        customTable();
    }
    
     private void customTable() {
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        tabThongTinMon.getTableHeader().setFont(new Font("Sanserif", Font.BOLD, 12));
        tabThongTinMon.getTableHeader().setBackground(new Color(50, 50, 50));
        tabThongTinMon.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        gradientPanel1 = new gui.component.GradientPanel();
        jLabel1 = new javax.swing.JLabel();
        tabbedPaneCustom1 = new gui.component.TabbedPaneCustom();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabThongTinMon = new javax.swing.JTable();
        tabbedPaneCustom2 = new gui.component.TabbedPaneCustom();
        jPanel2 = new javax.swing.JPanel();
        lblKH = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblGioHen = new javax.swing.JLabel();
        lblGioHuy = new javax.swing.JLabel();
        lblLoaiBan = new javax.swing.JLabel();
        lblTienCoc = new javax.swing.JLabel();
        lblHoanCoc = new javax.swing.JLabel();
        lblTienHoanLai = new javax.swing.JLabel();
        lblGioTre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblKH_V = new javax.swing.JLabel();
        lblSTD_V = new javax.swing.JLabel();
        lblGioHen_V = new javax.swing.JLabel();
        lblSoBan_V = new javax.swing.JLabel();
        lblGioHuy_V = new javax.swing.JLabel();
        lblTienCoc_V = new javax.swing.JLabel();
        lblGioTre_V = new javax.swing.JLabel();
        lblHoanCoc_V = new javax.swing.JLabel();
        lblTienHoanLai_V = new javax.swing.JLabel();
        button1 = new gui.component.Button();
        button2 = new gui.component.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gradientPanel1Layout = new javax.swing.GroupLayout(gradientPanel1);
        gradientPanel1.setLayout(gradientPanel1Layout);
        gradientPanel1Layout.setHorizontalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        gradientPanel1Layout.setVerticalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tabbedPaneCustom1.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabThongTinMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên món", "Giá", "Giá sau giảm", "Số lượng ", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tabThongTinMon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Danh sách các món ăn", jPanel1);

        tabbedPaneCustom2.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabbedPaneCustom2.setSelectedColor(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblKH.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblKH.setText("Khách hàng :");

        lblSDT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSDT.setText("Số điện thoại :");

        lblGioHen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGioHen.setText("Giờ hẹn :");

        lblGioHuy.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGioHuy.setText("Giờ hủy :");

        lblLoaiBan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLoaiBan.setText("Số bàn :");

        lblTienCoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTienCoc.setText("Tiền cọc  :");

        lblHoanCoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblHoanCoc.setText("Hoàn cọc(%) :");

        lblTienHoanLai.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTienHoanLai.setText("Tiền Hoàn  :");

        lblGioTre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGioTre.setText("So với hẹn:");

        lblKH_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblKH_V.setText("...");

        lblSTD_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSTD_V.setText("...");

        lblGioHen_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGioHen_V.setText("...");

        lblSoBan_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSoBan_V.setText("...");

        lblGioHuy_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGioHuy_V.setText("...");

        lblTienCoc_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTienCoc_V.setText("...");

        lblGioTre_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGioTre_V.setText("...");

        lblHoanCoc_V.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblHoanCoc_V.setText("...");

        lblTienHoanLai_V.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTienHoanLai_V.setText("...");

        button1.setBackground(new java.awt.Color(0, 0, 0));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Xác Nhận");
        button1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(204, 204, 204));
        button2.setForeground(new java.awt.Color(0, 0, 0));
        button2.setText("Thoát");
        button2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblHoanCoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGioHen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLoaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGioHuy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTienCoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGioTre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGioTre_V, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoanCoc_V, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTienCoc_V, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGioHuy_V, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoBan_V, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGioHen_V, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSTD_V, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKH_V, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTienHoanLai, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTienHoanLai_V, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKH)
                    .addComponent(lblKH_V))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDT)
                    .addComponent(lblSTD_V))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioHen)
                    .addComponent(lblGioHen_V))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiBan)
                    .addComponent(lblSoBan_V))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioHuy)
                    .addComponent(lblGioHuy_V))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienCoc)
                    .addComponent(lblTienCoc_V))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoanCoc)
                    .addComponent(lblHoanCoc_V))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioTre)
                    .addComponent(lblGioTre_V))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienHoanLai)
                    .addComponent(lblTienHoanLai_V))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneCustom2.addTab("Thông tin", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(gradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        CapNhatDonDatBan_Form.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        this.setVisible(false);
        CapNhatDonDatBan_Form.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try {
            DonDatBan_DAO dao = new DonDatBan_DAO();

            LocalDateTime now = LocalDateTime.now();

            int tienHoan = huyDinhDangVND(lblTienHoanLai_V.getText());

            if (dao.huyDonDatBan(ma, tienHoan, now, nv.getMaNV())) {
                JOptionPane.showMessageDialog(this, "Hủy thành công");
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Hủy thất bại");
                setVisible(false);
            }

        } catch (HeadlessException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void load(String maDDB) {

        DonDatBan_DAO dao = new DonDatBan_DAO();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        try {
            ArrayList<Object[]> list = dao.getChiTietDonDatBan(maDDB);
            Object[] ob = dao.getThongTinDonDatBan(maDDB);
            DefaultTableModel model = (DefaultTableModel) tabThongTinMon.getModel();
            model.getDataVector().removeAllElements();
            for (Object[] obj : list) {
                obj[1] = dinhDangVND(Double.parseDouble(obj[1].toString()));
                obj[2] = dinhDangVND(Double.parseDouble(obj[2].toString()));
                obj[4] = dinhDangVND(Double.parseDouble(obj[4].toString()));
                model.addRow(obj);
            }
            lblKH_V.setText(ob[0].toString());
            lblSTD_V.setText(ob[1].toString());
            lblGioHen_V.setText(ob[2].toString());
            lblSoBan_V.setText(ob[3].toString());
            lblGioHuy_V.setText(formatter.format(LocalDateTime.now()));
            lblTienCoc_V.setText(dinhDangVND(Double.parseDouble(ob[4].toString())));

            double gio = (double) Double.parseDouble(ob[5].toString()) / 60.0;
            
            System.out.println(ob[5].toString());
            
            int hoanCoc = 0;
            if (gio > 2) {
                hoanCoc = 70;
            } else if (gio < 1) {
                hoanCoc = 0;
            } else {
                hoanCoc = 50;
            }
            lblHoanCoc_V.setText(hoanCoc + " %");
            double tienHoan = (double) ob[4] * hoanCoc / 100.0;
            lblTienHoanLai_V.setText(dinhDangVND(tienHoan));
            lblGioTre_V.setText(String.format("%.2f", Math.abs(gio)) + " giờ");
        } catch (NumberFormatException | SQLException e) {
            e.printStackTrace();
        }

    }

    public String dinhDangVND(double x) {
        DecimalFormat decimalFormat = new DecimalFormat("#,###");
        String formatted = decimalFormat.format(x).replace(",", " ");

        return formatted + " VNĐ";
    }

    public int huyDinhDangVND(String s) {
        String newString[] = s.split("\\s+");
        String newS = "";
        for (int i = 0; i < newString.length - 1; i++) {
            newS += newString[i];
        }

        return Integer.parseInt(newS);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.component.Button button1;
    private gui.component.Button button2;
    private gui.component.GradientPanel gradientPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGioHen;
    private javax.swing.JLabel lblGioHen_V;
    private javax.swing.JLabel lblGioHuy;
    private javax.swing.JLabel lblGioHuy_V;
    private javax.swing.JLabel lblGioTre;
    private javax.swing.JLabel lblGioTre_V;
    private javax.swing.JLabel lblHoanCoc;
    private javax.swing.JLabel lblHoanCoc_V;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblKH_V;
    private javax.swing.JLabel lblLoaiBan;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSTD_V;
    private javax.swing.JLabel lblSoBan_V;
    private javax.swing.JLabel lblTienCoc;
    private javax.swing.JLabel lblTienCoc_V;
    private javax.swing.JLabel lblTienHoanLai;
    private javax.swing.JLabel lblTienHoanLai_V;
    private javax.swing.JTable tabThongTinMon;
    private gui.component.TabbedPaneCustom tabbedPaneCustom1;
    private gui.component.TabbedPaneCustom tabbedPaneCustom2;
    // End of variables declaration//GEN-END:variables
}
