/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.form;


import dao.MonAn_DAO;
import entity.KhuyenMai;
import entity.LoaiMonAn;
import entity.MonAn;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tamthanh
 */
public class ThongTinMonAn_Form extends javax.swing.JFrame {
    private MonAn_DAO dao_ma = new MonAn_DAO();
    private QuanLyMonAn_PN parentPanel = null;
    JTable table = null;
    DefaultTableModel tbm = null;
    private String selectedImagePath ;
    private String originalImagePath;
    private String tenAnh;
    /**
     * Creates new form form_Thongtinmon
     */
    public ThongTinMonAn_Form(String ma, QuanLyMonAn_PN parentPanel) {
        initComponents();
        this.parentPanel = parentPanel;
        table = parentPanel.getTable();
        tbm = parentPanel.getTableModel();
        setData(ma);
        setLocationRelativeTo(null);
        
        ButtonGroup groupTrangThai = new ButtonGroup();
        
        groupTrangThai.add(conmon);
        groupTrangThai.add(hetmon);
        
        mamon.setEnabled(false);
        loaimon.setEnabled(false);
        km.setEnabled(false);
    }
    //
    public void setData(String ma){
        MonAn m = dao_ma.TimTheoMa(ma);
        mamon.setText(m.getMaMA());
        tenmon.setText(m.getTenMA());
        
        gia.setText(String.valueOf(m.getGia()));
        loaimon.setText(m.getLoaiMonAn().getTenLoaiMA());
        if (m.getKhuyenMai() != null) {
        km.setText(m.getKhuyenMai().getMaKM());
        } else {
            km.setText(""); 
        }
       
        if (m.isTrangThai()) {
            conmon.setSelected(true);
            
           
        } else {
            hetmon.setSelected(true);
                    
        }
        // Lưu đường dẫn ảnh ban đầu
        originalImagePath = m.getHinhAnh();

        // Load ảnh từ đường dẫn ban đầu
        hinhAnh.setSize(185, 140);
        InputStream input = getClass().getResourceAsStream(originalImagePath);

        if (input != null) {
            try {
                BufferedImage image = ImageIO.read(input);
                Image scaledImage = image.getScaledInstance(hinhAnh.getWidth(), hinhAnh.getHeight(), Image.SCALE_SMOOTH);
                hinhAnh.setIcon(new ImageIcon(scaledImage));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mamon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tenmon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        conmon = new javax.swing.JRadioButton();
        hetmon = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        gia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hinhAnh = new javax.swing.JLabel();
        chonhinhanh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        km = new javax.swing.JTextField();
        loaimon = new javax.swing.JTextField();
        capnhat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        gradientPanel1 = new gui.component.GradientPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Món Ăn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 16))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Mã Món ăn :");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Tên Món ăn :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Trạng thái :");

        conmon.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        conmon.setForeground(new java.awt.Color(51, 204, 0));
        conmon.setText("Còn món");

        hetmon.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        hetmon.setForeground(new java.awt.Color(255, 0, 0));
        hetmon.setText("Hết món");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Giá Món ăn :");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Loại Món ăn :");

        hinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hinhAnh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        chonhinhanh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chonhinhanh.setText("Chọn hình ảnh");
        chonhinhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonhinhanhActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Khuyến mãi :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chonhinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(loaimon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenmon)
                            .addComponent(mamon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47)
                        .addComponent(gia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hetmon)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(conmon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE))
                            .addComponent(km))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(mamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(loaimon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chonhinhanh)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(conmon))
                .addGap(10, 10, 10)
                .addComponent(hetmon)
                .addContainerGap())
        );

        capnhat.setBackground(new java.awt.Color(51, 153, 0));
        capnhat.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        capnhat.setForeground(new java.awt.Color(255, 255, 255));
        capnhat.setText("Lưu dữ liệu");
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gradientPanel1Layout = new javax.swing.GroupLayout(gradientPanel1);
        gradientPanel1.setLayout(gradientPanel1Layout);
        gradientPanel1Layout.setHorizontalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        gradientPanel1Layout.setVerticalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(capnhat)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(gradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(gradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(capnhat))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void chonhinhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonhinhanhActionPerformed
            JFileChooser browseImageFile = new JFileChooser("src/hinhAnh");

            // Chỉ cho phép chọn các file ảnh
            FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
            browseImageFile.setFileFilter(fnef);

            int showOpenDialogue = browseImageFile.showOpenDialog(null);
            if(showOpenDialogue == JFileChooser.APPROVE_OPTION) {
                File selectedImageFile = browseImageFile.getSelectedFile();
                selectedImagePath = selectedImageFile.getAbsolutePath();
                tenAnh = selectedImageFile.getName();
                // Hiển thị đường dẫn ảnh để kiểm tra
                JOptionPane.showMessageDialog(null, selectedImagePath);

                // Gán biểu tượng mới cho `JLabel hinhAnh`
                ImageIcon ii = new ImageIcon(selectedImagePath);
                Image image = ii.getImage().getScaledInstance(hinhAnh.getWidth(), hinhAnh.getHeight(), Image.SCALE_SMOOTH);
                hinhAnh.setIcon(new ImageIcon(image));

                // Kiểm tra để đảm bảo hình ảnh được đặt lại
                hinhAnh.revalidate();
                hinhAnh.repaint();
            }
    }//GEN-LAST:event_chonhinhanhActionPerformed

    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
    String maMon = mamon.getText();
        String tenMon = tenmon.getText();
        String giaMon = gia.getText();
        String khuyenMai = km.getText();
        boolean trangThai = conmon.isSelected();
        String hinhAnh = "/hinhAnh/" + tenAnh;
        String loaimonan = loaimon.getText();
        
        float gia = 0;
        try {
            gia = Float.parseFloat(giaMon);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá món ăn không hợp lệ! Vui lòng nhập số.");
            return;
        }
        
        if (tenMon.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên món không hợp lệ!");
            return;
        }
        
        if (gia <= 0) {
            JOptionPane.showMessageDialog(null, "Giá món không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tạo đối tượng Mon với dữ liệu cập nhật
        MonAn updatedMon = new MonAn(maMon, tenMon, hinhAnh, gia, trangThai, new LoaiMonAn(loaimonan), new KhuyenMai(khuyenMai));

        // Gọi phương thức update trong DAO để lưu cập nhật vào DB
        if (dao_ma.CapNhatMonAn(updatedMon)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");

            // Cập nhật lại dữ liệu trên bảng
            int selectedRow = table.getSelectedRow();
            if (selectedRow != -1) {
                tbm.setValueAt(tenMon, selectedRow, 1);
                tbm.setValueAt(hinhAnh, selectedRow, 2);
                tbm.setValueAt(giaMon, selectedRow, 3);
                tbm.setValueAt(trangThai ? "Còn món" : "Hết món", selectedRow, 4);
                tbm.setValueAt(loaimonan, selectedRow, 5);
                tbm.setValueAt(khuyenMai, selectedRow, 6);
            }
            // Đóng form sau khi cập nhật
            parentPanel.refreshTable();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại.");
        }
        
    }//GEN-LAST:event_capnhatActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(form_Thongtinmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(form_Thongtinmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(form_Thongtinmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(form_Thongtinmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new form_Thongtinmon().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capnhat;
    private javax.swing.JButton chonhinhanh;
    private javax.swing.JRadioButton conmon;
    private javax.swing.JTextField gia;
    private gui.component.GradientPanel gradientPanel1;
    private javax.swing.JRadioButton hetmon;
    private javax.swing.JLabel hinhAnh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField km;
    private javax.swing.JTextField loaimon;
    private javax.swing.JTextField mamon;
    private javax.swing.JTextField tenmon;
    // End of variables declaration//GEN-END:variables
}
