/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import dao.KhachHang_DAO;
import gui.swing.table.TableCustom;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author THANHTRI
 */
public class TimKhachHang_PN extends javax.swing.JPanel {

    public TimKhachHang_PN() {
        initComponents();
        customTable();
    }
    
    private void customTable() {
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        tabThongTinKhachHang.getTableHeader().setFont(new Font("Sanserif", Font.BOLD, 12));
        tabThongTinKhachHang.getTableHeader().setBackground(new Color(50, 50, 50));
        tabThongTinKhachHang.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuChiTimKiem = new javax.swing.JLabel();
        cmbTieuChiTimKiem = new javax.swing.JComboBox<>();
        cmbTieuChiSapXep = new javax.swing.JComboBox<>();
        cmbLoaiKH = new javax.swing.JComboBox<>();
        radTang = new javax.swing.JRadioButton();
        radGiam = new javax.swing.JRadioButton();
        txtNhapThongTin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabThongTinKhachHang = new javax.swing.JTable();
        lblSapXep = new javax.swing.JLabel();
        lblLoaiNhanVien = new javax.swing.JLabel();
        lblNhapThongTin = new javax.swing.JLabel();
        lblLoaiNhanVien1 = new javax.swing.JLabel();
        cmbTrangThai = new javax.swing.JComboBox<>();
        btnTimKiem = new gui.component.Button();
        btnReset = new gui.component.Button();
        group = new ButtonGroup();

        group.add(radTang);
        group.add(radGiam);

        setBackground(java.awt.Color.white);
        setForeground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(980, 768));
        setVerifyInputWhenFocusTarget(false);

        lblTieuChiTimKiem.setBackground(java.awt.Color.black);
        lblTieuChiTimKiem.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTieuChiTimKiem.setText("Chọn tiêu chí tìm kiếm : ");

        cmbTieuChiTimKiem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbTieuChiTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn tiêu chí tìm kiếm--", "Mã khách hàng", "Số điện thoại", "Tên khách hàng" }));
        cmbTieuChiTimKiem.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbTieuChiTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTieuChiTimKiemActionPerformed(evt);
            }
        });

        cmbTieuChiSapXep.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbTieuChiSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn tiêu chí sắp xếp --", "Tên khách hàng", "Điểm tích lũy","Ngày lập","Ngày sinh"}));
        cmbTieuChiSapXep.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbTieuChiSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTieuChiSapXepActionPerformed(evt);
            }
        });

        cmbLoaiKH.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbLoaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Number", "Goal", "Platium" }));
        cmbLoaiKH.setName(""); // NOI18N
        cmbLoaiKH.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbLoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoaiNhanVienActionPerformed(evt);
            }
        });

        radTang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        radTang.setText("Tăng dần");
        radTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTangActionPerformed(evt);
            }
        });

        radGiam.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        radGiam.setText("Giảm dần");
        radGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radGiamActionPerformed(evt);
            }
        });

        txtNhapThongTin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNhapThongTin.setActionCommand("<Not Set>");
        txtNhapThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNhapThongTin.setPreferredSize(new java.awt.Dimension(50, 27));
        txtNhapThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapThongTinActionPerformed(evt);
            }
        });

        tabThongTinKhachHang.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tabThongTinKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Ngày lập","Ngày sinh", "Loại KH", "Điểm tích lũy", "Trạng thái"
            }
        ));
        tabThongTinKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabThongTinKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabThongTinNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabThongTinKhachHang);

        lblSapXep.setBackground(java.awt.Color.black);
        lblSapXep.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblSapXep.setText("Sắp xếp :");

        lblLoaiNhanVien.setBackground(java.awt.Color.black);
        lblLoaiNhanVien.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblLoaiNhanVien.setText("Loại khách hàng :");

        lblNhapThongTin.setBackground(java.awt.Color.black);
        lblNhapThongTin.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblNhapThongTin.setText("Nhập thông tin :");

        lblLoaiNhanVien1.setBackground(java.awt.Color.black);
        lblLoaiNhanVien1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblLoaiNhanVien1.setText("Trạng thái:");

        cmbTrangThai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang hoạt động", "Dừng hoạt động" }));
        cmbTrangThai.setName(""); // NOI18N
        cmbTrangThai.setPreferredSize(new java.awt.Dimension(50, 27));
        cmbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoaiNhanVien1ActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(50, 50, 50));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8-search-32.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        btnReset.setBackground(new java.awt.Color(50, 50, 50));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8-refresh-32.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTieuChiTimKiem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTieuChiSapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNhapThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbTieuChiTimKiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoaiNhanVien1)
                                    .addComponent(lblLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbLoaiKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radTang)
                                .addGap(18, 18, 18)
                                .addComponent(radGiam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cmbTieuChiSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLoaiNhanVien)
                                    .addComponent(cmbLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLoaiNhanVien1)
                                    .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTieuChiTimKiem)
                                    .addComponent(cmbTieuChiTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNhapThongTin)
                                    .addComponent(txtNhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(lblSapXep)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radTang)
                        .addComponent(radGiam)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnTimKiemActionPerformed(evt);
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                }
            }
        });

        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnResetActionPerformed(evt);
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                }
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTieuChiTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTieuChiTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTieuChiTimKiemActionPerformed

    private void txtNhapThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapThongTinActionPerformed

    private void radTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radTangActionPerformed

    private void radGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radGiamActionPerformed

    private void cmbLoaiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoaiNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLoaiNhanVienActionPerformed

    private void cmbTieuChiSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTieuChiSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTieuChiSapXepActionPerformed

    private void cmbLoaiNhanVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoaiNhanVien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLoaiNhanVien1ActionPerformed

    private void tabThongTinNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabThongTinNhanVienMouseClicked

     
    }//GEN-LAST:event_tabThongTinNhanVienMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        // TODO add your handling code here:
        deleteTableRow();
        if(checkValue() == false){
            return;
        }
        thucThi();
    }

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        deleteTableRow();
        cmbTieuChiTimKiem.setSelectedIndex(0);
        txtNhapThongTin.setText("");
        cmbLoaiKH.setSelectedIndex(0);
        cmbTieuChiSapXep.setSelectedIndex(0);
        cmbTrangThai.setSelectedIndex(0);
        radTang.setSelected(false);
        radGiam.setSelected(false);
    }


    public void thucThi() throws SQLException {
        KhachHang_DAO dao = new KhachHang_DAO();

        String tieuChiTimKiem = cmbTieuChiTimKiem.getSelectedItem().toString();
        String sapXep = cmbTieuChiSapXep.getSelectedItem().toString();
        String loaiKH = cmbLoaiKH.getSelectedItem().toString();
        String trangThai = cmbTrangThai.getSelectedItem().toString();
        String thongTin = txtNhapThongTin.getText();
        String tieuChiSapXep = radTang.isSelected() == true ? "ASC" : "DESC";


        if(loaiKH.equals("Tất cả") == true){
            loaiKH = "";
        }
        else if(loaiKH.equals("Number") == true){
            loaiKH = "LKH1";
        }
        else if(loaiKH.equals("Goal") == true){
            loaiKH = "LKH2";
        }
        else if(loaiKH.equals("Platium") == true){
            loaiKH = "LKH3";
        }


        if(trangThai.equals("Tất cả") == true){
            trangThai = "";
        }
        else if(trangThai.equals("Đang hoạt động") == true){
            trangThai = "1";
        }
        else if(trangThai.equals("Dừng hoạt động") == true){
            trangThai = "0";
        }


        if(sapXep.equals("-- Chọn tiêu chí sắp xếp --") == true){
            sapXep = "";
        }
        else if(sapXep.equals("Tên khách hàng") == true){
            sapXep = "tenKH";
        }
        else if(sapXep.equals("Điểm tích lũy") == true){
            sapXep = "DiemTL";
        }
        else if(sapXep.equals("Ngày lập") == true){
            sapXep = "ngayTao";
        }
        else if(sapXep.equals("Ngày sinh") == true){
            sapXep = "ngaySinh";
        }



        if(tieuChiTimKiem.equals("Mã khách hàng") == true){
            System.out.println("Mã khách hàng");
            Object[] ob = (Object[])dao.timKHTheoMa(thongTin,loaiKH,trangThai);
            if(ob == null || ob.length == 0){
                JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tabThongTinKhachHang.getModel();
            model.addRow(ob);
        }
        else if(tieuChiTimKiem.equals("Tên khách hàng") == true){
            System.out.println("Tên khách hàng");
            ArrayList<Object[]> list = dao.timKiemKHTheoTen(thongTin,loaiKH,trangThai,sapXep,tieuChiSapXep);
            if(list.size() == 0){
                JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) tabThongTinKhachHang.getModel();
            for(Object[] ob : list){
                model.addRow(ob);
            }
        }
        else if(tieuChiTimKiem.equals("Số điện thoại") == true){
            Object[] ob = (Object[])dao.timKHTheoSDT(thongTin,loaiKH,trangThai);
            if(ob == null || ob.length == 0){
                JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) tabThongTinKhachHang.getModel();
            model.addRow(ob);
        }


    }

    public void deleteTableRow(){
        DefaultTableModel model = (DefaultTableModel) tabThongTinKhachHang.getModel();
        model.getDataVector().removeAllElements();
    }

    public boolean checkValue(){
        String txtTieuChiTimKiem = cmbTieuChiTimKiem.getSelectedItem().toString();
        String txtSapXep = cmbTieuChiSapXep.getSelectedItem().toString();
        if(txtTieuChiTimKiem.equals("-- Chọn tiêu chí tìm kiếm --") == true){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tiêu chí tìm kiếm");
            return false;
        }
        else if(txtSapXep.equals("-- Chọn tiêu chí sắp xếp --") == false && (radGiam.isSelected() == false && radTang.isSelected() == false)){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tiêu chí sắp xếp");
            return false;
        }
        return true;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.component.Button btnReset;
    private gui.component.Button btnTimKiem;
    private javax.swing.JComboBox<String> cmbLoaiKH;
    private javax.swing.JComboBox<String> cmbTrangThai;
    private javax.swing.JComboBox<String> cmbTieuChiSapXep;
    private javax.swing.JComboBox<String> cmbTieuChiTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoaiNhanVien;
    private javax.swing.JLabel lblLoaiNhanVien1;
    private javax.swing.JLabel lblNhapThongTin;
    private javax.swing.JLabel lblSapXep;
    private javax.swing.JLabel lblTieuChiTimKiem;
    private javax.swing.JRadioButton radGiam;
    private javax.swing.JRadioButton radTang;
    private javax.swing.JTable tabThongTinKhachHang;
    private javax.swing.JTextField txtNhapThongTin;
    private javax.swing.ButtonGroup group;
    // End of variables declaration//GEN-END:variables


}
